name: Marco's Marketing
favicon: null
layout_spectrum: 0.75042
typography_spectrum: 0.9290615578647703
title: Servicio Exepcional. Resultados Exepcionales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040807'
    - '#3d62bb'
    - '#83a5d5'
    - '#dec37e'
    - '#8b655c'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
