name: Marco's Marketing
favicon: null
layout_spectrum: 0.9252826659940183
typography_spectrum: 0.9290615578647703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9653066652826965
  lightness: 0.6418895951937884
  saturation: 0.2938371514901519
  rhythmicContrast: 0.8096612279769033
purpose: []
